name: Django CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0  # Specify MySQL version
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Adjust to your Python version

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..15}; do
          mysql -h 127.0.0.1 -u root -proot -e "SELECT 1;" && break
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Update Django Database Settings for CI
      run: |
        sed -i 's/DATABASES = {.*}/DATABASES = {"default": {"ENGINE": "django.db.backends.mysql", "NAME": "testdb", "USER": "testuser", "PASSWORD": "testpass", "HOST": "127.0.0.1", "PORT": "3306",}}/' e2e/settings.py

    - name: Run Migrations
      working-directory: e2e  # Navigate to the folder containing manage.py
      run: |
        source ../venv/bin/activate
        python manage.py migrate

    - name: Run Tests
      working-directory: e2e  # Navigate to the folder containing manage.py
      run: |
        source ../venv/bin/activate
        python manage.py test
