name: Django CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirement.txt

      - name: Wait for MySQL to be Ready
        run: |
          for i in {1..15}; do
            mysql -h 127.0.0.1 -u root -proot -e "SELECT 1;" && break
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Migrations and Tests
        run: |
          source venv/bin/activate
          python manage.py migrate
          python manage.py test --keepdb

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HRKU-f9eeed2b-d695-4e73-841d-b68eac4a2957 }}
        run: |
          source venv/bin/activate
          heroku container:login
          heroku container:push web --app App-Test
          heroku container:release web --app App-Test
